# todo:
#  - use docker network for com between these (iirc i can even just use container names by default without this?)
#  - add traefik labels?

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: unless-stopped
    env_file: .env
    ports:
      - "8096:8096"
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/cache:/cache
      - ${MEDIA_ROOT}/tvshows:/data/tvshows
      - ${MEDIA_ROOT}/movies:/data/movies
    networks:
      - traefik-proxy
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.home.offsetmonkey538.top`)"
      - "traefik.http.routers.jellyfin.service=jellyfin"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"

  jellyseerr:
    image: fallenbagel/jellyseerr
    container_name: jellyseerr
    restart: unless-stopped
    env_file: .env
    environment:
      - LOG_LEVEL=debug
    #ports:
    #  - 5055:5055
    volumes:
      - ./jellyseerr_config:/app/config
    depends_on:
      - radarr
      - sonarr
    networks:
      - traefik-proxy
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.jellyseerr.rule=Host(`jellyseerr.home.offsetmonkey538.top`)"
      - "traefik.http.routers.jellyseerr.service=jellyseerr"
      - "traefik.http.services.jellyseerr.loadbalancer.server.port=5055"

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    env_file: .env
    #ports:
    #  - 8989:8989
    volumes:
      - ./sonarr_config:/config
      - ${MEDIA_ROOT}/tvshows:/tvshows
      - ${MEDIA_ROOT}/transmission/downloads/complete:/downloads/complete
    depends_on:
      - transmission
    networks:
      - traefik-proxy
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.sonarr.rule=Host(`sonarr.home.offsetmonkey538.top`)"
      - "traefik.http.routers.sonarr.service=sonarr"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    env_file: .env
    #ports:
    #  - 7878:7878
    volumes:
      - ./radarr_config:/config
      - ${MEDIA_ROOT}/transmission/downloads/complete:/downloads/complete
      - ${MEDIA_ROOT}/movies:/movies
    depends_on:
      - transmission
    networks:
      - traefik-proxy
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.radarr.rule=Host(`radarr.home.offsetmonkey538.top`)"
      - "traefik.http.routers.radarr.service=radarr"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"

  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    restart: unless-stopped
    env_file: .env
    #ports:
    #  - 6767:6767
    volumes:
      - ./bazarr_config:/config
      - ${MEDIA_ROOT}/movies:/movies
      - ${MEDIA_ROOT}/tvshows:/tvshows
    networks:
      - traefik-proxy
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.bazarr.rule=Host(`bazarr.home.offsetmonkey538.top`)"
      - "traefik.http.routers.bazarr.service=bazarr"
      - "traefik.http.services.bazarr.loadbalancer.server.port=6767"

  prowlarr:
    image: linuxserver/prowlarr
    container_name: prowlarr
    restart: unless-stopped
    env_file: .env
    #ports:
    #  - 9696:9696
    volumes:
      - ./prowlarr_config:/config
      - ${MEDIA_ROOT}/prowlarr/downloads:/downloads
    networks:
      - traefik-proxy
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.home.offsetmonkey538.top`)"
      - "traefik.http.routers.prowlarr.service=prowlarr"
      - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"

  flaresolverr:
    image: linuxserver/prowlarr
    container_name: flaresolverr
    restart: unless-stopped
    env_file: .env
    #ports:
    #  - 8191:8191

  transmission:
    image: linuxserver/transmission
    container_name: transmission
    restart: unless-stopped
    env_file: .env
    ports:
    #  - 9091:9091
      - "51413:51413"
      - "51413:51413/udp"
    volumes:
      - ./transmission_config:/config
      - ${MEDIA_ROOT}/transmission/downloads:/downloads
    networks:
      - traefik-proxy
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.transmission.rule=Host(`transmission.home.offsetmonkey538.top`)"
      - "traefik.http.routers.transmission.service=transmission"
      - "traefik.http.services.transmission.loadbalancer.server.port=9091"

networks:
  traefik-proxy:
    external: true