version: "3.5"

services:
  diun:
    image: crazymax/diun:latest
    container_name: diun
    command: serve
    volumes:
      - "./data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "TZ=Europe/Rome"
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
      - "DIUN_WATCH_WORKERS=20"
      - "DIUN_WATCH_SCHEDULE=0 12 * * *"
      - "DIUN_PROVIDERS_DOCKER=true"
      - "DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true"
      - "DIUN_NOTIF_DISCORD_WEBHOOKURL=https://discord.com/api/webhooks/xxxxxxxx/xxxxxxxxxxxxxxxxx"
      - "DIUN_NOTIF_DISCORD_RENDERFIELDS=true"
      - "DIUN_NOTIF_DISCORD_TIMEOUT=10s"
      - "DIUN_NOTIF_DISCORD_TEMPLATEBODY=A new version of {{ .Entry.Image.Path }} ({{ .Entry.Image.Tag }}) has been released."
    restart: always
