---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/widgets

#- logo: http://fc03.deviantart.net/fs71/f/2010/156/2/c/Nerv_Logo_by_maidenfan23.png

- resources:
    label: Melchior
    expanded: true
    cpu: true
    memory: true
    #disk: /

#- resources:
#    label: Backup Disk
#    expanded: true
#    disk: /mnt/backups/

- search:
    provider: custom
    url: https://searx.be/search?q=
    target: _blank
    focus: true

- datetime:
    text_size: xl
    format:
      timeStyle: short
      hour12: true
